### ISSUE TITLE
Not typing --base-dir before path to reads (when they are in a different directory) only runs get_lineage process

### ISSUE THREAD

**Issue by cajwalsh** [mhoban/eDNAFlow#20]
The first time I ran this, I forgot to include the --base-dir argument before my path to the fastqs. The pipeline did not fail, but instead did not use any reads and completed the workflow by only doing the get_lineage step before "successfully" finishing. Adding an error here or something here saying moving on with no reads or something would help with the desired functionality.

**Comment by mhoban** [comment]
Yeah the whole way directories and such are specified is a bit wonky. Currently --base-dir defaults to '.' (the directory you're sitting in. Maybe I'll have it default to blank and require it to be set to something and fail otherwise. There could be a few more layers of validation in several of the steps I think, as well.

**Comment by mhoban** [comment]
This should now be fixed as of 7aa28eadfeae28efb55ffe6fbdd654f399ed26c7 (or indeed a little earlier, but definitely here).

I just added a sanity check to make sure the directory exists. Also, you now use --reads instead of --base-dir because that's more intuitive (although --base-dir still works)
